// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXqViY_2ecqCJ9dNmF2JFNI_tH79WlEI',
    appId: '1:59873367224:web:608fd4dfe23425e182904d',
    messagingSenderId: '59873367224',
    projectId: 'employeemanagment-766bf',
    authDomain: 'employeemanagment-766bf.firebaseapp.com',
    storageBucket: 'employeemanagment-766bf.firebasestorage.app',
    measurementId: 'G-WR9Z9YT5Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyT9A3FYZvAXp5IIt37SGoeAZIeUIAi14',
    appId: '1:59873367224:android:f4cf185f5d59b0c482904d',
    messagingSenderId: '59873367224',
    projectId: 'employeemanagment-766bf',
    storageBucket: 'employeemanagment-766bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyP78ICdhUwS4Oc_FsDIT4xN674jDRoQ',
    appId: '1:59873367224:ios:2695dfee6da792e682904d',
    messagingSenderId: '59873367224',
    projectId: 'employeemanagment-766bf',
    storageBucket: 'employeemanagment-766bf.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCyP78ICdhUwS4Oc_FsDIT4xN674jDRoQ',
    appId: '1:59873367224:ios:2695dfee6da792e682904d',
    messagingSenderId: '59873367224',
    projectId: 'employeemanagment-766bf',
    storageBucket: 'employeemanagment-766bf.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXqViY_2ecqCJ9dNmF2JFNI_tH79WlEI',
    appId: '1:59873367224:web:dc645c830c4e7a9182904d',
    messagingSenderId: '59873367224',
    projectId: 'employeemanagment-766bf',
    authDomain: 'employeemanagment-766bf.firebaseapp.com',
    storageBucket: 'employeemanagment-766bf.firebasestorage.app',
    measurementId: 'G-TN4KDRJC9S',
  );

}